#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Configuration variables
custom_server_name="howtogeek.com"
redirection_url="https://www.howtogeek.com/666395/how-to-use-the-sed-command-on-linux/redirect-page"
replacement_content="server_name $custom_server_name;\n\trewrite ^\/redirect_me $redirection_url permanent;"

# Replace server_name and add redirection in Nginx configuration
sudo sed -i "s/server_name _;/$replacement_content/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
