#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements


redirecton="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/nXlnx8nZyE?si=ZF9kPvIFQTqUHwp6\n\t}\n"
file="/etc/nginx/sites-available/default"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee  /var/www/html/index.nginx-debian.html
sed -i "10i\ $redirection" "$file"

service nginx restart
