#!/usr/bin/env bash
# script that installs and configures haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get install -y haproxy=2.0.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 255205-web-01 100.26.56.12:80 check
   server 255205-web-02 54.237.207.207:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
