#!/usr/bin/env bash
# This script loops and displays bad luck for the 4th loop iteration, good luck on the 8th and best school for the rest
n=1

while [ $n -le 10 ]
do
    if [ $n -eq 4 ]
    then
        echo "bad luck"
    elif [ $n -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    n=$(( n + 1 ))
done
