#!/usr/bin/env bash
# This script displays "bad luck from China" 4th iteration, "bad luck from Japan" on the 9th iteration, and "bad luck from Italy" for ther 17th iteration
n=1

while [ $n -le 20 ]
do
    echo $n
    case $n in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    n=$(( n + 1 ))
done
